[2025-07-14 01:58:59] [INFO] infrastructure.kafka_consumer: Esperando mensajes de TLE...
[2025-07-14 01:59:12] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: schema "np" does not exist
LINE 4: ...z,'2025-07-14T03:00:23.530766+00:00'::timestamptz,np.float64...
                                                             ^
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 55, in consume_tle_messages
    handle_tle_message(conn, value)
  File "/app/application/orchestrator.py", line 54, in handle_tle_message
    save_pass_activities(conn, valid_passes)
  File "/app/infrastructure/db.py", line 58, in save_pass_activities
    execute_values(cur, sql, values, template=None, page_size=100)
  File "/usr/local/lib/python3.11/site-packages/psycopg2/extras.py", line 1299, in execute_values
    cur.execute(b''.join(parts))
psycopg2.errors.InvalidSchemaName: schema "np" does not exist
LINE 4: ...z,'2025-07-14T03:00:23.530766+00:00'::timestamptz,np.float64...
                                                             ^

[2025-07-14 01:59:12] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: current transaction is aborted, commands ignored until end of transaction block
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 55, in consume_tle_messages
    handle_tle_message(conn, value)
  File "/app/application/orchestrator.py", line 16, in handle_tle_message
    tle = process_and_save_tle(conn, value)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/application/tle_service.py", line 32, in process_and_save_tle
    save_tle_data(conn, tle_data)
  File "/app/infrastructure/db.py", line 69, in save_tle_data
    cur.execute(query, (
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

[2025-07-14 01:59:12] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: current transaction is aborted, commands ignored until end of transaction block
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 55, in consume_tle_messages
    handle_tle_message(conn, value)
  File "/app/application/orchestrator.py", line 16, in handle_tle_message
    tle = process_and_save_tle(conn, value)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/application/tle_service.py", line 32, in process_and_save_tle
    save_tle_data(conn, tle_data)
  File "/app/infrastructure/db.py", line 69, in save_tle_data
    cur.execute(query, (
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

[2025-07-14 01:59:12] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: current transaction is aborted, commands ignored until end of transaction block
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 55, in consume_tle_messages
    handle_tle_message(conn, value)
  File "/app/application/orchestrator.py", line 16, in handle_tle_message
    tle = process_and_save_tle(conn, value)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/application/tle_service.py", line 32, in process_and_save_tle
    save_tle_data(conn, tle_data)
  File "/app/infrastructure/db.py", line 69, in save_tle_data
    cur.execute(query, (
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

[2025-07-14 01:59:12] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: current transaction is aborted, commands ignored until end of transaction block
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 55, in consume_tle_messages
    handle_tle_message(conn, value)
  File "/app/application/orchestrator.py", line 16, in handle_tle_message
    tle = process_and_save_tle(conn, value)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/application/tle_service.py", line 32, in process_and_save_tle
    save_tle_data(conn, tle_data)
  File "/app/infrastructure/db.py", line 69, in save_tle_data
    cur.execute(query, (
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

[2025-07-14 01:59:12] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: current transaction is aborted, commands ignored until end of transaction block
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 55, in consume_tle_messages
    handle_tle_message(conn, value)
  File "/app/application/orchestrator.py", line 16, in handle_tle_message
    tle = process_and_save_tle(conn, value)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/application/tle_service.py", line 32, in process_and_save_tle
    save_tle_data(conn, tle_data)
  File "/app/infrastructure/db.py", line 69, in save_tle_data
    cur.execute(query, (
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

[2025-07-14 01:59:12] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: current transaction is aborted, commands ignored until end of transaction block
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 55, in consume_tle_messages
    handle_tle_message(conn, value)
  File "/app/application/orchestrator.py", line 16, in handle_tle_message
    tle = process_and_save_tle(conn, value)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/application/tle_service.py", line 32, in process_and_save_tle
    save_tle_data(conn, tle_data)
  File "/app/infrastructure/db.py", line 69, in save_tle_data
    cur.execute(query, (
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

[2025-07-14 01:59:12] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: current transaction is aborted, commands ignored until end of transaction block
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 55, in consume_tle_messages
    handle_tle_message(conn, value)
  File "/app/application/orchestrator.py", line 16, in handle_tle_message
    tle = process_and_save_tle(conn, value)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/application/tle_service.py", line 32, in process_and_save_tle
    save_tle_data(conn, tle_data)
  File "/app/infrastructure/db.py", line 69, in save_tle_data
    cur.execute(query, (
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

[2025-07-14 01:59:12] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: current transaction is aborted, commands ignored until end of transaction block
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 55, in consume_tle_messages
    handle_tle_message(conn, value)
  File "/app/application/orchestrator.py", line 16, in handle_tle_message
    tle = process_and_save_tle(conn, value)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/application/tle_service.py", line 32, in process_and_save_tle
    save_tle_data(conn, tle_data)
  File "/app/infrastructure/db.py", line 69, in save_tle_data
    cur.execute(query, (
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

[2025-07-14 01:59:12] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: current transaction is aborted, commands ignored until end of transaction block
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 55, in consume_tle_messages
    handle_tle_message(conn, value)
  File "/app/application/orchestrator.py", line 16, in handle_tle_message
    tle = process_and_save_tle(conn, value)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/application/tle_service.py", line 32, in process_and_save_tle
    save_tle_data(conn, tle_data)
  File "/app/infrastructure/db.py", line 69, in save_tle_data
    cur.execute(query, (
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

[2025-07-14 01:59:12] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: current transaction is aborted, commands ignored until end of transaction block
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 55, in consume_tle_messages
    handle_tle_message(conn, value)
  File "/app/application/orchestrator.py", line 16, in handle_tle_message
    tle = process_and_save_tle(conn, value)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/application/tle_service.py", line 32, in process_and_save_tle
    save_tle_data(conn, tle_data)
  File "/app/infrastructure/db.py", line 69, in save_tle_data
    cur.execute(query, (
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

[2025-07-14 01:59:12] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: current transaction is aborted, commands ignored until end of transaction block
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 55, in consume_tle_messages
    handle_tle_message(conn, value)
  File "/app/application/orchestrator.py", line 16, in handle_tle_message
    tle = process_and_save_tle(conn, value)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/application/tle_service.py", line 32, in process_and_save_tle
    save_tle_data(conn, tle_data)
  File "/app/infrastructure/db.py", line 69, in save_tle_data
    cur.execute(query, (
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

[2025-07-14 01:59:12] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: current transaction is aborted, commands ignored until end of transaction block
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 55, in consume_tle_messages
    handle_tle_message(conn, value)
  File "/app/application/orchestrator.py", line 16, in handle_tle_message
    tle = process_and_save_tle(conn, value)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/application/tle_service.py", line 32, in process_and_save_tle
    save_tle_data(conn, tle_data)
  File "/app/infrastructure/db.py", line 69, in save_tle_data
    cur.execute(query, (
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

[2025-07-14 01:59:12] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: current transaction is aborted, commands ignored until end of transaction block
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 55, in consume_tle_messages
    handle_tle_message(conn, value)
  File "/app/application/orchestrator.py", line 16, in handle_tle_message
    tle = process_and_save_tle(conn, value)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/application/tle_service.py", line 32, in process_and_save_tle
    save_tle_data(conn, tle_data)
  File "/app/infrastructure/db.py", line 69, in save_tle_data
    cur.execute(query, (
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

[2025-07-14 01:59:12] [ERROR] infrastructure.kafka_consumer: Error procesando mensaje: current transaction is aborted, commands ignored until end of transaction block
Traceback (most recent call last):
  File "/app/infrastructure/kafka_consumer.py", line 55, in consume_tle_messages
    handle_tle_message(conn, value)
  File "/app/application/orchestrator.py", line 16, in handle_tle_message
    tle = process_and_save_tle(conn, value)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/application/tle_service.py", line 32, in process_and_save_tle
    save_tle_data(conn, tle_data)
  File "/app/infrastructure/db.py", line 69, in save_tle_data
    cur.execute(query, (
psycopg2.errors.InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

[2025-07-14 02:16:24] [INFO] infrastructure.kafka_consumer: Esperando mensajes de TLE...
[2025-07-14 02:16:42] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-14 02:16:42] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-14 02:16:42] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-14 02:16:42] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
[2025-07-14 02:16:42] [INFO] infrastructure.kafka_consumer: Mensaje procesado con éxito.
